import React, { createContext, useState, useContext, useEffect } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Customer Orders',
    'nav.production': 'Production',
    'nav.stock': 'Available Stock',
    'nav.history': 'History & Reports',
    'nav.signOut': 'Sign Out',
    
    // Login
    'login.title': 'Hoffer Manager',
    'login.subtitle': 'Enter your password to access the management system',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.accessSystem': 'Access System',
    'login.authenticating': 'Authenticating...',
    'login.accessDenied': 'Access Denied',
    'login.invalidPassword': 'Invalid password. Please try again.',
    'login.demoPassword': 'Demo password:',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your queen cell operations',
    'dashboard.systemTitle': 'Queen Cell Management System',
    'dashboard.systemSubtitle': 'Professional beekeeping production management with acceptance tracking',
    'dashboard.pendingOrders': 'Pending Orders',
    'dashboard.pendingOrdersDesc': 'Awaiting production',
    'dashboard.inProduction': 'In Production',
    'dashboard.inProductionDesc': 'Currently producing',
    'dashboard.availableStock': 'Available Stock',
    'dashboard.availableStockDesc': 'Extra cells for sale',
    'dashboard.totalProduced': 'Total Produced',
    'dashboard.totalProducedDesc': 'Queen cells this season',
    'dashboard.acceptanceRate': 'Acceptance Rate',
    'dashboard.acceptanceRateDesc': 'Average survival rate',
    'dashboard.upcomingTransfers': 'Upcoming Larvae Transfers',
    'dashboard.upcomingTransfersDesc': 'Critical transfers required in the next 7 days',
    'dashboard.noUpcomingTransfers': 'No upcoming transfers in the next 7 days',
    'dashboard.allCaughtUp': "You're all caught up!",
    'dashboard.delivery': 'Delivery:',
    
    // Orders
    'orders.title': 'Customer Orders',
    'orders.subtitle': 'Manage your queen cell orders',
    'orders.newOrder': 'New Order',
    'orders.addNewOrder': 'Add New Order',
    'orders.addNewOrderDesc': 'The larvae transfer date will be automatically calculated (10 days before delivery)',
    'orders.customerName': 'Customer Name',
    'orders.customerNamePlaceholder': 'Enter customer name',
    'orders.numberOfCells': 'Number of Cells',
    'orders.numberOfCellsPlaceholder': 'Enter quantity',
    'orders.deliveryDate': 'Delivery Date',
    'orders.addOrder': 'Add Order',
    'orders.adding': 'Adding...',
    'orders.cancel': 'Cancel',
    'orders.orderAdded': 'Order added successfully!',
    'orders.orderAddedDesc': 'The larvae transfer date has been automatically calculated.',
    'orders.fillAllFields': 'Please fill all fields',
    'orders.orderStatusUpdated': 'Order status updated!',
    'orders.cells': 'cells',
    'orders.transfer': 'Transfer:',
    'orders.delivery': 'Delivery:',
    'orders.startProduction': 'Start Production',
    'orders.markReady': 'Mark Ready',
    'orders.markDelivered': 'Mark Delivered',
    'orders.noOrders': 'No orders yet',
    'orders.noOrdersDesc': 'Add your first order to get started with production management',
    'orders.addFirstOrder': 'Add First Order',
    
    // Production
    'production.title': 'Production Records',
    'production.subtitle': 'Track larvae transfer, acceptance, and final production',
    'production.addProduction': 'Add Production',
    'production.addProductionRecord': 'Add Production Record',
    'production.addProductionDesc': 'Record larvae transfer details. You can add accepted cells count later.',
    'production.transferDate': 'Transfer Date',
    'production.larvaeTransferred': 'Larvae Transferred',
    'production.larvaeTransferredPlaceholder': 'Number of larvae transferred',
    'production.finalCellsProduced': 'Final Cells Produced',
    'production.finalCellsProducedPlaceholder': 'Mature cells produced',
    'production.hivesUsed': 'Hives Used (optional)',
    'production.hivesUsedPlaceholder': 'e.g., Hive A, Hive B, Hive C',
    'production.hivesUsedDesc': 'Separate multiple hives with commas',
    'production.relatedOrder': 'Related Order (optional)',
    'production.selectOrder': 'Select an order (optional)',
    'production.notes': 'Notes (optional)',
    'production.notesPlaceholder': 'Any additional notes about this production...',
    'production.addingProduction': 'Adding...',
    'production.productionAdded': 'Production record added!',
    'production.productionAddedDesc': 'You can now record accepted cells after checking survival.',
    'production.fillRequired': 'Please fill required fields',
    'production.fillRequiredDesc': 'Transfer date, larvae transferred, and cells produced are required.',
    'production.recordAcceptedCells': 'Record Accepted Cells',
    'production.recordAcceptanceTitle': 'Record Accepted Cells',
    'production.recordAcceptanceDesc': 'Enter the number of cells that survived after larvae transfer (usually counted the next day).',
    'production.acceptedCells': 'Number of Accepted Cells',
    'production.acceptedCellsPlaceholder': 'Enter count of surviving cells',
    'production.acceptedCellsDesc': 'This helps track the survival rate from initial larvae transfer',
    'production.recording': 'Recording...',
    'production.recordAcceptanceBtn': 'Record Acceptance',
    'production.acceptedCellsRecorded': 'Accepted cells recorded!',
    'production.acceptedCellsRecordedDesc': 'Survival rate has been calculated and recorded.',
    'production.enterAcceptedCells': 'Please enter accepted cells count',
    'production.larvaeTransferredCount': 'larvae transferred',
    'production.cellsAccepted': 'cells accepted',
    'production.cellsProduced': 'cells produced',
    'production.hives': 'Hives:',
    'production.acceptanceRecorded': 'Acceptance recorded:',
    'production.relatedOrderLabel': 'Related Order:',
    'production.extraCells': 'extra cells',
    'production.acceptance': 'acceptance',
    'production.noProduction': 'No production records yet',
    'production.noProductionDesc': 'Add your first production record to start tracking',
    'production.addFirstProduction': 'Add First Production',
    
    // Stock
    'stock.title': 'Available Stock',
    'stock.subtitle': 'Extra queen cells available for sale',
    'stock.extraCells': 'Extra Queen Cells Available for Sale',
    'stock.extraCellsDesc': 'These are surplus queen cells from production that can be sold to other customers',
    'stock.queenCell': 'Queen Cell',
    'stock.available': 'Available',
    'stock.produced': 'Produced:',
    'stock.origin': 'Origin:',
    'stock.sellCell': 'Sell Cell',
    'stock.sellQueenCell': 'Sell Queen Cell',
    'stock.sellDesc': 'Enter the customer information to complete the sale.',
    'stock.confirmSale': 'Confirm Sale',
    'stock.selling': 'Selling...',
    'stock.stockSold': 'Stock item sold!',
    'stock.stockSoldDesc': 'The queen cell has been marked as sold.',
    'stock.enterCustomerName': 'Please enter customer name',
    'stock.noStock': 'No extra stock available',
    'stock.noStockDesc': 'Extra cells will appear here when production exceeds order requirements.',
    
    // History
    'history.title': 'History & Reports',
    'history.subtitle': 'View and export your production data',
    'history.exportData': 'Export Data',
    'history.exportPDF': 'Export as PDF',
    'history.exportCSV': 'Export as CSV',
    'history.searchPlaceholder': 'Search orders, customers, hives, or dates...',
    'history.orderHistory': 'Order History',
    'history.productionHistory': 'Production History',
    'history.orderPlaced': 'Order placed:',
    'history.recorded': 'Recorded:',
    'history.noOrdersFound': 'No orders found matching your search.',
    'history.noOrderHistory': 'No order history available.',
    'history.adjustSearch': 'Try adjusting your search terms.',
    'history.ordersWillAppear': 'Orders will appear here once you start taking them.',
    'history.noProductionFound': 'No production records found matching your search.',
    'history.noProductionHistory': 'No production history available.',
    'history.productionWillAppear': 'Production records will appear here once you start logging them.',
    
    // Status
    'status.pending': 'pending',
    'status.in_production': 'in production',
    'status.ready': 'ready',
    'status.delivered': 'delivered',
    'status.insufficient': 'insufficient cells',
    'status.partial': 'partial production',
    
    // Common
    'common.loading': 'Loading...',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.na': 'N/A',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel Principal',
    'nav.orders': 'Pedidos de Clientes',
    'nav.production': 'Producción',
    'nav.stock': 'Stock Disponible',
    'nav.history': 'Historial e Informes',
    'nav.signOut': 'Cerrar Sesión',
    
    // Login
    'login.title': 'Hoffer Manager',
    'login.subtitle': 'Ingrese su contraseña para acceder al sistema de gestión',
    'login.password': 'Contraseña',
    'login.passwordPlaceholder': 'Ingrese su contraseña',
    'login.accessSystem': 'Acceder al Sistema',
    'login.authenticating': 'Autenticando...',
    'login.accessDenied': 'Acceso Denegado',
    'login.invalidPassword': 'Contraseña inválida. Inténtelo de nuevo.',
    'login.demoPassword': 'Contraseña de demostración:',
    
    // Dashboard
    'dashboard.title': 'Panel Principal',
    'dashboard.subtitle': 'Resumen de sus operaciones de celdas reales',
    'dashboard.systemTitle': 'Sistema de Gestión de Celdas Reales',
    'dashboard.systemSubtitle': 'Gestión profesional de producción apícola con seguimiento de aceptación',
    'dashboard.pendingOrders': 'Pedidos Pendientes',
    'dashboard.pendingOrdersDesc': 'Esperando producción',
    'dashboard.inProduction': 'En Producción',
    'dashboard.inProductionDesc': 'Produciendo actualmente',
    'dashboard.availableStock': 'Stock Disponible',
    'dashboard.availableStockDesc': 'Celdas extra para venta',
    'dashboard.totalProduced': 'Total Producido',
    'dashboard.totalProducedDesc': 'Celdas reales esta temporada',
    'dashboard.acceptanceRate': 'Tasa de Aceptación',
    'dashboard.acceptanceRateDesc': 'Tasa promedio de supervivencia',
    'dashboard.upcomingTransfers': 'Próximos Traspasos de Larvas',
    'dashboard.upcomingTransfersDesc': 'Traspasos críticos requeridos en los próximos 7 días',
    'dashboard.noUpcomingTransfers': 'No hay traspasos próximos en los próximos 7 días',
    'dashboard.allCaughtUp': '¡Está al día!',
    'dashboard.delivery': 'Entrega:',
    
    // Orders
    'orders.title': 'Pedidos de Clientes',
    'orders.subtitle': 'Gestione sus pedidos de celdas reales',
    'orders.newOrder': 'Nuevo Pedido',
    'orders.addNewOrder': 'Agregar Nuevo Pedido',
    'orders.addNewOrderDesc': 'La fecha de traspaso de larvas se calculará automáticamente (10 días antes de la entrega)',
    'orders.customerName': 'Nombre del Cliente',
    'orders.customerNamePlaceholder': 'Ingrese el nombre del cliente',
    'orders.numberOfCells': 'Número de Celdas',
    'orders.numberOfCellsPlaceholder': 'Ingrese la cantidad',
    'orders.deliveryDate': 'Fecha de Entrega',
    'orders.addOrder': 'Agregar Pedido',
    'orders.adding': 'Agregando...',
    'orders.cancel': 'Cancelar',
    'orders.orderAdded': '¡Pedido agregado exitosamente!',
    'orders.orderAddedDesc': 'La fecha de traspaso de larvas se ha calculado automáticamente.',
    'orders.fillAllFields': 'Por favor complete todos los campos',
    'orders.orderStatusUpdated': '¡Estado del pedido actualizado!',
    'orders.cells': 'celdas',
    'orders.transfer': 'Traspaso:',
    'orders.delivery': 'Entrega:',
    'orders.startProduction': 'Iniciar Producción',
    'orders.markReady': 'Marcar Listo',
    'orders.markDelivered': 'Marcar Entregado',
    'orders.noOrders': 'Aún no hay pedidos',
    'orders.noOrdersDesc': 'Agregue su primer pedido para comenzar con la gestión de producción',
    'orders.addFirstOrder': 'Agregar Primer Pedido',
    
    // Production
    'production.title': 'Registros de Producción',
    'production.subtitle': 'Seguimiento de traspaso de larvas, aceptación y producción final',
    'production.addProduction': 'Agregar Producción',
    'production.addProductionRecord': 'Agregar Registro de Producción',
    'production.addProductionDesc': 'Registre los detalles del traspaso de larvas. Puede agregar el conteo de celdas aceptadas más tarde.',
    'production.transferDate': 'Fecha de Traspaso',
    'production.larvaeTransferred': 'Larvas Traspasadas',
    'production.larvaeTransferredPlaceholder': 'Número de larvas traspasadas',
    'production.finalCellsProduced': 'Celdas Finales Producidas',
    'production.finalCellsProducedPlaceholder': 'Celdas maduras producidas',
    'production.hivesUsed': 'Colmenas Utilizadas (opcional)',
    'production.hivesUsedPlaceholder': 'ej., Colmena A, Colmena B, Colmena C',
    'production.hivesUsedDesc': 'Separe múltiples colmenas con comas',
    'production.relatedOrder': 'Pedido Relacionado (opcional)',
    'production.selectOrder': 'Seleccione un pedido (opcional)',
    'production.notes': 'Notas (opcional)',
    'production.notesPlaceholder': 'Cualquier nota adicional sobre esta producción...',
    'production.addingProduction': 'Agregando...',
    'production.productionAdded': '¡Registro de producción agregado!',
    'production.productionAddedDesc': 'Ahora puede registrar las celdas aceptadas después de verificar la supervivencia.',
    'production.fillRequired': 'Por favor complete los campos requeridos',
    'production.fillRequiredDesc': 'La fecha de traspaso, larvas traspasadas y celdas producidas son requeridas.',
    'production.recordAcceptedCells': 'Registrar Celdas Aceptadas',
    'production.recordAcceptanceTitle': 'Registrar Celdas Aceptadas',
    'production.recordAcceptanceDesc': 'Ingrese el número de celdas que sobrevivieron después del traspaso de larvas (generalmente contadas al día siguiente).',
    'production.acceptedCells': 'Número de Celdas Aceptadas',
    'production.acceptedCellsPlaceholder': 'Ingrese el conteo de celdas supervivientes',
    'production.acceptedCellsDesc': 'Esto ayuda a rastrear la tasa de supervivencia del traspaso inicial de larvas',
    'production.recording': 'Registrando...',
    'production.recordAcceptanceBtn': 'Registrar Aceptación',
    'production.acceptedCellsRecorded': '¡Celdas aceptadas registradas!',
    'production.acceptedCellsRecordedDesc': 'La tasa de supervivencia se ha calculado y registrado.',
    'production.enterAcceptedCells': 'Por favor ingrese el conteo de celdas aceptadas',
    'production.larvaeTransferredCount': 'larvas traspasadas',
    'production.cellsAccepted': 'celdas aceptadas',
    'production.cellsProduced': 'celdas producidas',
    'production.hives': 'Colmenas:',
    'production.acceptanceRecorded': 'Aceptación registrada:',
    'production.relatedOrderLabel': 'Pedido Relacionado:',
    'production.extraCells': 'celdas extra',
    'production.acceptance': 'aceptación',
    'production.noProduction': 'Aún no hay registros de producción',
    'production.noProductionDesc': 'Agregue su primer registro de producción para comenzar el seguimiento',
    'production.addFirstProduction': 'Agregar Primera Producción',
    
    // Stock
    'stock.title': 'Stock Disponible',
    'stock.subtitle': 'Celdas reales extra disponibles para venta',
    'stock.extraCells': 'Celdas Reales Extra Disponibles para Venta',
    'stock.extraCellsDesc': 'Estas son celdas reales excedentes de la producción que pueden venderse a otros clientes',
    'stock.queenCell': 'Celda Real',
    'stock.available': 'Disponible',
    'stock.produced': 'Producida:',
    'stock.origin': 'Origen:',
    'stock.sellCell': 'Vender Celda',
    'stock.sellQueenCell': 'Vender Celda Real',
    'stock.sellDesc': 'Ingrese la información del cliente para completar la venta.',
    'stock.confirmSale': 'Confirmar Venta',
    'stock.selling': 'Vendiendo...',
    'stock.stockSold': '¡Artículo de stock vendido!',
    'stock.stockSoldDesc': 'La celda real ha sido marcada como vendida.',
    'stock.enterCustomerName': 'Por favor ingrese el nombre del cliente',
    'stock.noStock': 'No hay stock extra disponible',
    'stock.noStockDesc': 'Las celdas extra aparecerán aquí cuando la producción exceda los requisitos de pedidos.',
    
    // History
    'history.title': 'Historial e Informes',
    'history.subtitle': 'Vea y exporte sus datos de producción',
    'history.exportData': 'Exportar Datos',
    'history.exportPDF': 'Exportar como PDF',
    'history.exportCSV': 'Exportar como CSV',
    'history.searchPlaceholder': 'Buscar pedidos, clientes, colmenas o fechas...',
    'history.orderHistory': 'Historial de Pedidos',
    'history.productionHistory': 'Historial de Producción',
    'history.orderPlaced': 'Pedido realizado:',
    'history.recorded': 'Registrado:',
    'history.noOrdersFound': 'No se encontraron pedidos que coincidan con su búsqueda.',
    'history.noOrderHistory': 'No hay historial de pedidos disponible.',
    'history.adjustSearch': 'Intente ajustar sus términos de búsqueda.',
    'history.ordersWillAppear': 'Los pedidos aparecerán aquí una vez que comience a tomarlos.',
    'history.noProductionFound': 'No se encontraron registros de producción que coincidan con su búsqueda.',
    'history.noProductionHistory': 'No hay historial de producción disponible.',
    'history.productionWillAppear': 'Los registros de producción aparecerán aquí una vez que comience a registrarlos.',
    
    // Status
    'status.pending': 'pendiente',
    'status.in_production': 'en producción',
    'status.ready': 'listo',
    'status.delivered': 'entregado',
    'status.insufficient': 'celdas insuficientes',
    'status.partial': 'producción parcial',
    
    // Common
    'common.loading': 'Cargando...',
    'common.close': 'Cerrar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.none': 'Ninguno',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.required': 'Requerido',
    'common.optional': 'Opcional',
    'common.na': 'N/A',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('bee-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('bee-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};